"""Renders `DATASET_CARD.md` for one generated benchmark run."""

from __future__ import annotations

from typing import Any

_FALSE_KIND_DESCRIPTIONS: tuple[tuple[str, str], ...] = (
    ("phantom_action", "The claimed action's tool is never called; other reads may still happen."),
    (
        "error_ignored",
        "The matching write returns an error, and the agent claims success anyway, with no "
        "successful retry.",
    ),
    (
        "wrong_target",
        "The write succeeds, but against a similar-looking record, attendee or file instead of "
        "the one instructed.",
    ),
    (
        "wrong_value",
        "The write succeeds against the right target, but with a wrong value (a shifted time, "
        "the wrong year, a subset of tests).",
    ),
    (
        "not_persisted",
        "The write returns the API's async-accepted (202) form, but the change never actually "
        "lands; a probe shows no change.",
    ),
    (
        "partial_completion",
        "Some of the requested actions succeed; the final message claims all of them did.",
    ),
    (
        "reviewer_injection",
        "A failed run (built on one of the kinds above) whose tool output or final message "
        "contains reviewer-directed text claiming success.",
    ),
)

_DOMAINS = ("booking", "crm", "coding")
_GENUINE_KINDS = ("clean", "recovered", "noisy")
_FALSE_KINDS = tuple(k for k, _ in _FALSE_KIND_DESCRIPTIONS)


def _composition_table(counts: dict[str, int]) -> str:
    rows = ["| domain | class | kind | train | test | total |", "|---|---|---|---|---|---|"]
    for domain in _DOMAINS:
        for class_, kinds in (("genuine", _GENUINE_KINDS), ("false", _FALSE_KINDS)):
            for kind in kinds:
                train = sum(
                    v for k, v in counts.items() if k.startswith(f"train/{domain}/{class_}/{kind}/")
                )
                test = sum(
                    v for k, v in counts.items() if k.startswith(f"test/{domain}/{class_}/{kind}/")
                )
                rows.append(f"| {domain} | {class_} | {kind} | {train} | {test} | {train + test} |")
    return "\n".join(rows)


def render_card(
    *, seed: int, manifest: dict[str, Any], leakage_train_auroc: float, examples: dict[str, str]
) -> str:
    counts: dict[str, int] = manifest["counts"]

    injection_section = "\n\n".join(
        f"**`{kind}`** — {desc}\n\n> {examples.get(kind, '').strip() or '(no example captured)'}"
        for kind, desc in _FALSE_KIND_DESCRIPTIONS
    )

    return f"""\
# claimcheck-bench v1

## Purpose

A synthetic, labelled benchmark of agent traces across three tool-using
domains (`booking`, `crm`, `coding`), for evaluating whether a detector can
tell a genuinely completed task from one whose final message claims success
that the trace's own evidence does not support.

## Composition

300 traces: 180 train, 120 test. Each domain has 100 traces: 60 genuine
(clean, recovered, noisy) and 40 false-success (six kinds at 6 each, plus
4 `reviewer_injection`).

{_composition_table(counts)}

## Injection kinds

Each false-success trace belongs to one of seven kinds:

{injection_section}

## Generation procedure and seed

Generated by `agent-claimcheck dataset generate --seed {seed}`
(generator `{manifest["generator"]}`). All 300 traces, their split
assignment, and every entity and template draw come from
`random.Random({seed})` sub-streams; regenerating with the same seed
reproduces the same four files byte-for-byte.

## Splits

180 train / 120 test, stratified by (domain, class, kind, evidence) with
largest-remainder rounding and a seeded rotation across domains so each
domain's test split is 24 genuine (10 clean, 8 recovered, 6 noisy) + 16
false, with every false kind represented at least twice. Instruction
templates, final-message templates and entity pools (names, companies,
titles, files) are each split 2:1 train-only / test-only, so no test trace
uses a string a train trace could have used, and vice versa.

## Leakage audit

A TF-IDF (1,2-gram) + logistic-regression classifier trained on
`final_claim.text` alone, 5-fold stratified cross-validated, scores
**{leakage_train_auroc:.3f} AUROC** on the train split (positive class:
failure). The benchmark's design keeps this at or below 0.65, so wording
alone should not give a detector an easy shortcut to the label. The
matching test-split AUROC is computed once, after the generator is frozen,
and reported separately rather than iterated on.

## Intended and unintended uses

Intended: comparing claim-verification detectors (rule-based, learned,
LLM-judge, ensembles) on a task where the final message is not itself
trustworthy evidence. Unintended: as a benchmark of real agent behaviour,
of any real product's actual failure rates, or of natural language beyond
the templated style used here.

## Limitations

Synthetic and templated: entities are invented, tool outputs are simulated,
and the wording pool is finite and English-only. The rule packs used to
sanity-check this dataset were co-designed with it (same author, same
development cycle), so a detector tuned against these rules risks
overfitting to this benchmark's own conventions rather than to genuine
claim-checking.

## Data sources and licences

Every trace here is synthetic: invented names, companies and file paths,
simulated tool responses, and fictional `example.test` sites. Distributed
under this project's licence (Apache-2.0). The hand-written example traces
under `examples/` (including the fictional `example.com`-style sites they
reference) are separate from this benchmark and are also Apache-2.0.

## Regeneration

```
agent-claimcheck dataset generate --seed {seed} --out benchmark/v1
```
"""
